name: E2E tests

on: [push]

jobs:
   cypress-run:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v2
         - name: Start strapi server
           run: cd backend && docker-compose up -d
         - name: Install PNPM
           run: corepack enable && corepack prepare pnpm@7.0.0-rc.6 --activate
         - name: Install workspaces
           run: pnpm install
         - name: Cypress run
           uses: cypress-io/github-action@v2
           env:
              CYPRESS_NODE_ENV: test
              NEXT_PUBLIC_STRAPI_ORIGIN: http://localhost:1337
           with:
              working-directory: frontend
              install: false
              build: pnpm run build
              start: pnpm start
