name: Type Check

on: push

jobs:
   tsc:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v2
         - name: Install pnpm
           uses: pnpm/action-setup@v2.0.1
           with:
              version: 7
              run_install: false
         - name: Install workspaces
           env:
              FONT_AWESOME_NPM_TOKEN: ${{ secrets.FONT_AWESOME_NPM_TOKEN }}
           run: pnpm install:all
         - name: Run Typescript Compiler
           run: pnpm type-check
